var Products =
[
  {
    "product_id": "1",
    "title": "Nestlé Nesquik Cereals",
    "category": "Grocery",
    "description": "Neque porro quisquam est qui dolore ipsum quia dolor sit amet.",
    "price": 4.50,
    "rating": 4.10,
    "img_url": "Images/nesquick.png",
    "beforeDiscount": "",
    "discount_tag":"",
    "brand":"Nestle",
  },
  {
    "product_id": "2",
    "title": "Vanilla Almond Milkins",
    "category": "Dairy",
    "description": "Neque porro quisquam est qui dolore ipsum quia dolor sit amet.",
    "price": 2.40,
    "rating": 4.3,
    "img_url": "Images/armondMilk.png",
    "beforeDiscount": "",
    "discount_tag":"",
    "brand":"Amul",
  },
  {
    "product_id": "3",
    "title": "Kraft Cheddar Cheese",
    "category": "Dairy",
    "description": "Neque porro quisquam est qui dolore ipsum quia dolor sit amet.",
    "price": 3.50,
    "rating": 4.9,
    "img_url": "Images/cheese.png",
    "beforeDiscount": 4.80,
    "discount_tag":"Images/cheese.png",
    "brand":"Chedder",
  },
  {
    "product_id": "4",
    "title": "Lurpak Unsalted Butter",
    "category": "Grocery",
    "description": "Neque porro quisquam est qui dolore ipsum quia dolor sit amet.",
    "price": 58.50,
    "rating": 4.5,
    "img_url": "Images/luprak.png",
    "beforeDiscount": "",
    "discount_tag":"",
    "brand":"Nestle",
  },
  
  ];