
var Products =
  [
    {
      "product_id": "1",
      "title": "Nestlé Nesquik Cereals",
      "category": "Grocery",
      "description": "Neque porro quisquam est qui dolore ipsum quia dolor sit amet.",
      "price": 4.50,
      "rating": 4.1,
      "img_url": "Images/nesquick.png",
      "quantity": 1,
      "discount_price": "",
    },
    {
      "product_id": "2",
      "title": "Vanilla Almond Milkins",
      "category": "Dairy",
      "description": "Neque porro quisquam est qui dolore ipsum quia dolor sit amet.",
      "price": 2.40,
      "rating": 4.3,
      "img_url": "Images/armondMilk.png",
      "quantity": 1,
      "discount_price": 350.00,
    },
    {
      "product_id": "3",
      "title": "Nestlé Chocolate MiloE",
      "category": "Dairy",
      "description": "Neque porro quisquam est qui dolore ipsum quia dolor sit amet.",
      "price": 3.50,
      "rating": 4.9,
      "img_url": "Images/milo.png",
      "quantity": 1,
      "discount_price": 400.00,
    },
    {
      "product_id": "4",
      "title": "Nutella Chocolate Hazr",
      "category": "Grocery",
      "description": "Neque porro quisquam est qui dolore ipsum quia dolor sit amet.",
      "price": 58.50,
      "rating": 4.5,
      "img_url": "Images/nutella.png",
      "quantity": 1,
      "discount_price": "",
    },
    {
      "product_id": "5",
      "title": "Nestlé Nesquik Cerelac",
      "category": "Dairy",
      "description": "Neque porro quisquam est qui dolore ipsum quia dolor sit amet.",
      "price": 3.50,
      "rating": 4.9,
      "img_url": "Images/ceriel.png",
      "quantity" : 1,
      "discount_price": 280.00,
    },
    {
      "product_id": "6",
      "title": "Kraft Cheddar Cheese",
      "category": "Dairy",
      "description": "Neque porro quisquam est qui dolore ipsum quia dolor sit amet.",
      "price": 2.40,
      "rating": 4.3,
      "img_url": "Images/cheese-kraft.png",
      "quantity" : 1,
      "discount_price": "",
    },
    {
      "product_id": "7",
      "title": "CORN COB",
      "category": "Grocery",
      "description": "Homegrown fresh corn",
      "price": 80.00,
      "rating": 4,
      "img_url":"corn.png",
      "quantity" : 1,
      "discount_price": "",
    },
    {
      "product_id": "8",
      "title": "LIFEBUOY HANDWASH",
      "category": "HEALTH & BEAUTY",
      "description": "Lifebuoy cool fresh lemon scented ",
      "price": 120.00,
      "rating": 4,
      "img_url":"Images/handwash.png",
      "quantity" : 1,
      "discount_price": 90.00,
    },
    {
      "product_id": "9",
      "title": "KOTTU MEE NOODLES",
      "category": "Grocery",
      "description": "Hot and Spicy chicken flavoured",
      "price": 80.00,
      "rating": 4,
      "img_url":"Images/noodles.png",
      "quantity" : 1,
      "discount_price": "",
    },
    {
      "product_id": "10",
      "title": "KNORR PASTA",
      "category": "Grocery",
      "description": "Fusilli pasta with broccoli and cheesy sauce",
      "price": 280.00,
      "rating": 4,
      "img_url":"Images/sausages.png",
      "quantity" : 1,
      "discount_price": 250.00,
    },
    {
      "product_id": "11",
      "title": "LUX MAGICAL BEAUTY SOAP",
      "category": "Health & Beauty",
      "description": "For a long lasting enchanting fragnance",
      "price": 60.00,
      "rating": 4,
      "img_url":"Images/Lux.png",
      "quantity" : 1,
      "discount_price": "",
    },
    {
      "product_id": "12",
      "title": "PORK SAUSAGES",
      "category": "Meats & Seafood",
      "description": "Premium birchwood smoked sausages",
      "price": 280.00,
      "rating": 4,
      "img_url":"Images/sausages.png",
      "quantity" : 1,
      "discount_price": 250.00,
    },
    {
      "product_id": "13",
      "title": "BROCCOLI",
      "category": "Grocery",
      "description": "Fresh farm grown broccoli",
      "price": 130.00,
      "rating": 4,
      "img_url":"Images/broccoli.png",
      "quantity" : 1,
      "discount_price": 100.00,
    },
    {
      "product_id": "14",
      "title": "SIGNAL TOOTHPASTE",
      "category": "Health & Beauty",
      "description": "Pro sensitive relief and repair",
      "price": 100.00,
      "rating": 4,
      "img_url":"Images/toothpaste.png",
      "quantity" : 1,
      "discount_price": "",
    },
    {
      "product_id": "15",
      "title": "SHAFER RED WINE",
      "category": "Spirits & Wines",
      "description": "2007 Napa Valley Stags Leap District",
      "price": 2850.00,
      "rating": 4,
      "img_url":"Images/wine.png",
      "quantity" : 1,
      "discount_price": 2500.00,
    },
    {
      "product_id": "16",
      "title": "CAMPBELLS SOUP",
      "category": "Canned goods & soups",
      "description": "Minestrone with italian sausage",
      "price": 280,
      "rating": 4,
      "img_url":"Images/soup.png",
      "quantity" : 1,
      "discount_price": 250,
    },
    {
      "product_id": "17",
      "title": "SPRITE BOTTLE",
      "category": "Grocery",
      "description": "Fizzy drink",
      "price": 300.00,
      "rating": 4,
      "img_url":"Images/sprite.png",
      "quantity" : 1,
      "discount_price": 270.00,
    }]
